apiVersion: v2
name: spegel
description: Stateless cluster local OCI registry mirror.
type: application
version: 0.7.0
appVersion: v0.7.0
annotations:
  artifacthub.io/category: "integration-delivery"
  artifacthub.io/license: "MIT"
  artifacthub.io/operator: "false"
  artifacthub.io/prerelease: "false"
